version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: market
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d market"]
      interval: 1s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/.env:/root/.env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
  
  python_app:
    build:
      context: ./backend
      dockerfile: Dockerfile.python
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/.env:/root/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"

volumes:
  postgres_data: